[package]
name = "oceanfs-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Workspace
oceanfs-hash.workspace = true
bytes.workspace = true
smallvec.workspace = true
uuid.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
prost.workspace = true
tonic.workspace = true

# External
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }

[build-dependencies]
tonic-build.workspace = true

[dev-dependencies]
static_assertions.workspace = true

[lints]
workspace = true
