[package]
name = "oceanfs-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
oceanfs-core.workspace = true
oceanfs-routing.workspace = true
oceanfs-membership.workspace = true
oceanfs-network.workspace = true
oceanfs-storage.workspace = true
oceanfs-cache.workspace = true
bytes.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio-test = "0.4"

[lints]
workspace = true
