//! CUDA-accelerated erasure coding backend.
//!
//! Offloads batch GF(2^8) matrix multiplication to the GPU.
//! Only compiled when the `cuda` feature is enabled.
//!
//! ## Architecture
//!
//! ```text
//! CudaBackend::encode(data_shards, m):
//!   1. Build split-tables for the encoding matrix (32 bytes per coefficient)
//!   2. Upload tables + data to GPU global memory
//!   3. Launch gf256_encode kernel: one thread per byte position
//!   4. Download parity shards from GPU
//!   5. Free device memory
//!
//! Kernel: gf256_encode
//!   Grid:  ceil(num_bytes / 256)
//!   Block: 256 threads
//!   Each thread: computes one byte of each parity shard using
//!   split-table GF(2^8) lookup (same algorithm as NEON path).
//! ```
//!
//! ## Safety
//!
//! CUDA kernel launches use `unsafe` through `cudarc`. Each `unsafe` block
//! is preceded by a `// SAFETY:` comment. `cudarc` provides safe device
//! memory management; unsafe is limited to kernel argument construction.

#[cfg(not(no_nvcomp))]
pub(crate) mod nvcomp;

use std::{
    sync::{
        atomic::{AtomicBool, Ordering},
        Arc,
    },
    time::Instant,
};

use bytes::Bytes;
use cudarc::driver::{CudaDevice, CudaFunction, LaunchAsync, LaunchConfig};
use oceanfs_core::{Counter, Gauge, GpuConfig, LabelSet, MetricRegistrar};
use oceanfs_ec::{Decoder, Encoder, Error as EcError, Result as EcResult};
use tokio::sync::Semaphore;

/// Queries total GPU memory in bytes via the CUDA driver API.
///
/// Returns 0 if the query fails.
fn query_gpu_total_memory() -> u64 {
    cudarc::driver::result::mem_get_info().map(|(_free, total)| total as u64).unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Embedded PTX kernel (generated by build.rs from kernels/gf256_encode.cu)
// ---------------------------------------------------------------------------

/// PTX source for the GF(2^8) encode kernel.
const PTX_SRC: &str = include_str!("../../kernels/gf256_encode.ptx");
/// Module name for the loaded PTX.
const PTX_MODULE: &str = "gf256_encode";
/// Kernel function name.
const PTX_FN: &str = "gf256_encode";

// ---------------------------------------------------------------------------
// GF(2^8) split-table construction (same algorithm as NEON path)
// ---------------------------------------------------------------------------

struct GfMulTable {
    lo: [u8; 16],
    hi: [u8; 16],
}

impl GfMulTable {
    fn new(coeff: u8) -> Self {
        let mut lo = [0u8; 16];
        let mut hi = [0u8; 16];
        for i in 0..16u8 {
            lo[i as usize] = gf_mul_portable(coeff, i);
            hi[i as usize] = gf_mul_portable(coeff, i.wrapping_mul(16));
        }
        Self { lo, hi }
    }
}

struct GpuEncodeTables {
    data: Vec<u8>,
    #[allow(dead_code)]
    k: u8,
    #[allow(dead_code)]
    m: u8,
}

impl GpuEncodeTables {
    fn new(k: u8, m: u8) -> Self {
        let ki = k as usize;
        let mi = m as usize;
        let num_coeffs = ki * mi;
        let total = 2 * 16 * num_coeffs;
        let mut data = vec![0u8; total];

        for row in 0..mi {
            for col in 0..ki {
                let x = (col + 1) as u8;
                let y = (ki + row + 1) as u8;
                let coeff = gf_inv_portable(x ^ y);
                let table = GfMulTable::new(coeff);
                let base = row * ki * 16 + col * 16;
                data[base..base + 16].copy_from_slice(&table.lo);
                data[num_coeffs * 16 + base..num_coeffs * 16 + base + 16]
                    .copy_from_slice(&table.hi);
            }
        }
        Self { data, k, m }
    }
}

// ---------------------------------------------------------------------------
// Portable GF(2^8) arithmetic (table construction only — NOT on the hot path)
// ---------------------------------------------------------------------------

static GF_LOG: [u8; 256] = [
    0, 0, 1, 25, 2, 50, 26, 198, 3, 223, 51, 238, 27, 104, 199, 75, 4, 100, 224, 14, 52, 141, 239,
    129, 28, 193, 105, 248, 200, 8, 76, 113, 5, 138, 101, 47, 225, 36, 15, 33, 53, 147, 142, 218,
    240, 18, 130, 69, 29, 181, 194, 125, 106, 39, 249, 185, 201, 154, 9, 120, 77, 228, 114, 166, 6,
    191, 139, 98, 102, 221, 48, 253, 226, 152, 37, 179, 16, 145, 34, 136, 54, 208, 148, 206, 143,
    150, 219, 189, 241, 210, 19, 92, 131, 56, 70, 64, 30, 66, 182, 163, 195, 72, 126, 110, 107, 58,
    40, 84, 250, 133, 186, 61, 202, 94, 155, 159, 10, 21, 121, 43, 78, 212, 229, 172, 115, 243,
    167, 87, 7, 112, 192, 247, 140, 128, 99, 13, 103, 74, 222, 237, 49, 197, 254, 24, 227, 165,
    153, 119, 38, 184, 180, 124, 17, 68, 146, 217, 35, 32, 137, 46, 55, 63, 209, 91, 149, 188, 207,
    205, 144, 135, 151, 178, 220, 252, 190, 97, 242, 86, 211, 171, 20, 42, 93, 158, 132, 60, 57,
    83, 71, 109, 65, 162, 31, 45, 67, 216, 183, 123, 164, 118, 196, 23, 73, 236, 127, 12, 111, 246,
    108, 161, 59, 82, 41, 157, 85, 170, 251, 96, 134, 177, 187, 204, 62, 90, 203, 89, 95, 176, 156,
    169, 160, 81, 11, 245, 22, 235, 122, 117, 44, 215, 79, 174, 213, 233, 230, 231, 173, 232, 116,
    214, 244, 234, 168, 80, 88, 175,
];

static GF_EXP: [u8; 512] = [
    1, 2, 4, 8, 16, 32, 64, 128, 29, 58, 116, 232, 205, 135, 19, 38, 76, 152, 45, 90, 180, 117,
    234, 201, 143, 3, 6, 12, 24, 48, 96, 192, 157, 39, 78, 156, 37, 74, 148, 53, 106, 212, 181,
    119, 238, 193, 159, 35, 70, 140, 5, 10, 20, 40, 80, 160, 93, 186, 105, 210, 185, 111, 222, 161,
    95, 190, 97, 194, 153, 47, 94, 188, 101, 202, 137, 15, 30, 60, 120, 240, 253, 231, 211, 187,
    107, 214, 177, 127, 254, 225, 223, 163, 91, 182, 113, 226, 217, 175, 67, 134, 17, 34, 68, 136,
    13, 26, 52, 104, 208, 189, 103, 206, 129, 31, 62, 124, 248, 237, 199, 147, 59, 118, 236, 197,
    151, 51, 102, 204, 133, 23, 46, 92, 184, 109, 218, 169, 79, 158, 33, 66, 132, 21, 42, 84, 168,
    77, 154, 41, 82, 164, 85, 170, 73, 146, 57, 114, 228, 213, 183, 115, 230, 209, 191, 99, 198,
    145, 63, 126, 252, 229, 215, 179, 123, 246, 241, 255, 227, 219, 171, 75, 150, 49, 98, 196, 149,
    55, 110, 220, 165, 87, 174, 65, 130, 25, 50, 100, 200, 141, 7, 14, 28, 56, 112, 224, 221, 167,
    83, 166, 81, 162, 89, 178, 121, 242, 249, 239, 195, 155, 43, 86, 172, 69, 138, 9, 18, 36, 72,
    144, 61, 122, 244, 245, 247, 243, 251, 235, 203, 139, 11, 22, 44, 88, 176, 125, 250, 233, 207,
    131, 27, 54, 108, 216, 173, 71, 142, 1, 2, 4, 8, 16, 32, 64, 128, 29, 58, 116, 232, 205, 135,
    19, 38, 76, 152, 45, 90, 180, 117, 234, 201, 143, 3, 6, 12, 24, 48, 96, 192, 157, 39, 78, 156,
    37, 74, 148, 53, 106, 212, 181, 119, 238, 193, 159, 35, 70, 140, 5, 10, 20, 40, 80, 160, 93,
    186, 105, 210, 185, 111, 222, 161, 95, 190, 97, 194, 153, 47, 94, 188, 101, 202, 137, 15, 30,
    60, 120, 240, 253, 231, 211, 187, 107, 214, 177, 127, 254, 225, 223, 163, 91, 182, 113, 226,
    217, 175, 67, 134, 17, 34, 68, 136, 13, 26, 52, 104, 208, 189, 103, 206, 129, 31, 62, 124, 248,
    237, 199, 147, 59, 118, 236, 197, 151, 51, 102, 204, 133, 23, 46, 92, 184, 109, 218, 169, 79,
    158, 33, 66, 132, 21, 42, 84, 168, 77, 154, 41, 82, 164, 85, 170, 73, 146, 57, 114, 228, 213,
    183, 115, 230, 209, 191, 99, 198, 145, 63, 126, 252, 229, 215, 179, 123, 246, 241, 255, 227,
    219, 171, 75, 150, 49, 98, 196, 149, 55, 110, 220, 165, 87, 174, 65, 130, 25, 50, 100, 200,
    141, 7, 14, 28, 56, 112, 224, 221, 167, 83, 166, 81, 162, 89, 178, 121, 242, 249, 239, 195,
    155, 43, 86, 172, 69, 138, 9, 18, 36, 72, 144, 61, 122, 244, 245, 247, 243, 251, 235, 203, 139,
    11, 22, 44, 88, 176, 125, 250, 233, 207, 131, 27, 54, 108, 216, 173, 71, 142, 1, 2,
];

#[inline]
fn gf_mul_portable(a: u8, b: u8) -> u8 {
    if a == 0 || b == 0 {
        return 0;
    }
    let sum = GF_LOG[a as usize] as u16 + GF_LOG[b as usize] as u16;
    GF_EXP[(sum % 255) as usize]
}

#[inline]
fn gf_inv_portable(a: u8) -> u8 {
    if a == 0 {
        return 0;
    }
    GF_EXP[(255 - GF_LOG[a as usize] as usize) % 255]
}

// ---------------------------------------------------------------------------
// CudaBackend
// ---------------------------------------------------------------------------

/// A CUDA-accelerated EC backend.
///
/// Implements `Encoder` using GPU kernel launches for batched stripe
/// operations. Decode delegates to the CPU Cauchy RS (less frequent path).
pub struct CudaBackend {
    /// CUDA device handle.
    device: Arc<CudaDevice>,
    /// GPU configuration.
    config: GpuConfig,
    /// Semaphore bounding concurrent GPU operations (per ADR-0006 §4).
    encode_semaphore: Arc<Semaphore>,
    /// Whether the GPU is currently available.
    available: AtomicBool,
    /// GPU utilization gauge (1=available, 0=unavailable).
    gpu_utilization: Gauge,
    /// GPU memory gauge (total bytes).
    gpu_memory_bytes: Gauge,
    /// Cumulative GPU encode time in microseconds.
    gpu_encode_us_total: Counter,
}

impl CudaBackend {
    /// Creates a new CUDA backend, probing for a GPU device.
    ///
    /// # Returns
    ///
    /// `None` if no CUDA device is detected or kernel compilation fails.
    pub fn new(config: GpuConfig) -> Option<Self> {
        let device = match CudaDevice::new(config.device_id) {
            Ok(dev) => {
                tracing::info!(
                    device_id = config.device_id,
                    name = dev.name().unwrap_or_default(),
                    "CUDA device initialized"
                );
                dev
            }
            Err(e) => {
                tracing::debug!(
                    device_id = config.device_id,
                    error = %e,
                    "CUDA device not available"
                );
                return None;
            }
        };

        // Load the PTX kernel module
        if let Err(e) = device.load_ptx(PTX_SRC.into(), PTX_MODULE, &[PTX_FN]) {
            tracing::error!(error = %e, "Failed to load CUDA PTX module");
            return None;
        }
        tracing::debug!("CUDA kernel {} loaded", PTX_FN);

        let encode_semaphore = Arc::new(Semaphore::new(config.max_concurrent_ops));

        // Query total GPU memory.
        let mem_bytes = query_gpu_total_memory();

        let gpu_mem = Gauge::new(
            "accel_gpu_memory_bytes".into(),
            "Total GPU memory bytes".into(),
            LabelSet::empty(),
        );
        gpu_mem.set(mem_bytes);

        let gpu_util = Gauge::new(
            "accel_gpu_utilization".into(),
            "GPU availability (1=healthy, 0=unhealthy)".into(),
            LabelSet::empty(),
        );
        gpu_util.set(1); // GPU is healthy at startup

        Some(Self {
            device,
            config,
            encode_semaphore,
            available: AtomicBool::new(true),
            gpu_utilization: gpu_util,
            gpu_memory_bytes: gpu_mem,
            gpu_encode_us_total: Counter::new(
                "accel_gpu_encode_us_total".into(),
                "Cumulative GPU encode time in microseconds".into(),
                LabelSet::empty(),
            ),
        })
    }

    /// Returns a handle to the compiled kernel function.
    fn get_kernel(&self) -> Option<CudaFunction> {
        self.device.get_func(PTX_MODULE, PTX_FN)
    }

    /// Returns `true` if the CUDA device is currently available.
    pub fn is_available(&self) -> bool {
        self.available.load(Ordering::Relaxed)
    }

    /// Marks the GPU as unavailable.
    pub fn mark_unavailable(&self) {
        self.available.store(false, Ordering::Relaxed);
        self.gpu_utilization.set(0);
        tracing::error!("CUDA device marked unavailable; entering cooldown");
    }

    /// Returns the GPU configuration.
    pub fn config(&self) -> &GpuConfig {
        &self.config
    }

    /// Determines whether a segment should use GPU acceleration.
    pub fn should_use_gpu(&self, segment_size_bytes: u64) -> bool {
        self.is_available() && segment_size_bytes >= self.config.min_segment_size
    }

    /// Registers GPU metrics with a registrar.
    pub fn register_metrics(&self, registrar: &dyn MetricRegistrar) {
        registrar.register_gauge(self.gpu_utilization.clone());
        registrar.register_gauge(self.gpu_memory_bytes.clone());
        registrar.register_counter(self.gpu_encode_us_total.clone());
    }
}

// ---------------------------------------------------------------------------
// Encoder implementation (GPU-accelerated)
// ---------------------------------------------------------------------------

impl Encoder for CudaBackend {
    fn encode(&self, data_shards: &[&[u8]], parity_count: u8) -> EcResult<Vec<Bytes>> {
        let start = Instant::now();
        let result = self.encode_impl(data_shards, parity_count);
        let elapsed_us = start.elapsed().as_micros() as u64;
        self.gpu_encode_us_total.add(elapsed_us);
        result
    }
}

impl CudaBackend {
    fn encode_impl(&self, data_shards: &[&[u8]], parity_count: u8) -> EcResult<Vec<Bytes>> {
        if !self.is_available() {
            return Err(EcError::DecodingFailed("GPU backend is unavailable (cooldown)".into()));
        }

        let m = parity_count;
        if m == 0 {
            return Ok(Vec::new());
        }
        let k = data_shards.len() as u8;
        if k == 0 {
            return Ok(Vec::new());
        }
        let shard_size = data_shards.first().map(|s| s.len()).unwrap_or(0);
        if shard_size == 0 {
            return Ok(vec![Bytes::new(); m as usize]);
        }

        // Build split-tables and flatten data
        let tables = GpuEncodeTables::new(k, m);
        let mut flat_data = Vec::with_capacity(k as usize * shard_size);
        for shard in data_shards {
            flat_data.extend_from_slice(shard);
        }

        // Verify kernel is available
        if self.get_kernel().is_none() {
            return Err(EcError::DecodingFailed("CUDA kernel not loaded".into()));
        }

        // Acquire GPU semaphore permit (per ADR-0006 §4).
        // try_acquire is non-blocking; if no permit available, return error
        // so the caller can fall back to CPU or retry.
        let _permit = self.encode_semaphore.try_acquire().map_err(|_| {
            EcError::DecodingFailed("GPU saturated — no semaphore permits available".into())
        })?;

        let num_bytes = shard_size as i32;
        let m_usize = m as usize;

        // --- GPU operations ---
        let result = (|| -> Result<Vec<Bytes>, cudarc::driver::DriverError> {
            // SAFETY: Device memory allocation on a valid, initialized CudaDevice.
            // The returned CudaSlice wraps a valid GPU pointer or returns Err.
            let mut d_data = unsafe { self.device.alloc::<u8>(flat_data.len()) }?;
            // SAFETY: Same — valid device allocation.
            let d_parity = unsafe { self.device.alloc::<u8>(m_usize * shard_size) }?;
            // SAFETY: Same — valid device allocation.
            let mut d_tables = unsafe { self.device.alloc::<u8>(tables.data.len()) }?;

            // Copy host → device
            self.device.htod_sync_copy_into(&flat_data, &mut d_data)?;
            self.device.htod_sync_copy_into(&tables.data, &mut d_tables)?;

            // Get kernel function (already verified above)
            #[allow(clippy::unwrap_used)]
            let kernel = self.get_kernel().unwrap();

            let block_dim: u32 = 256;
            let grid_dim: u32 = (num_bytes as u32).div_ceil(block_dim);

            let cfg = LaunchConfig {
                grid_dim: (grid_dim, 1, 1),
                block_dim: (block_dim, 1, 1),
                shared_mem_bytes: 0,
            };

            // SAFETY: d_data, d_parity, d_tables are valid device allocations
            // from this device. Parameter types match the kernel signature
            // (const u8*, u8*, const u8*, int, int, int).
            unsafe {
                kernel.launch(
                    cfg,
                    (
                        &d_data,   // *const u8 data
                        &d_parity, // *mut u8 parity (CudaSlice is DevicePtr)
                        &d_tables, // *const u8 tables
                        k as i32,  // int k
                        m as i32,  // int m
                        num_bytes, // int num_bytes
                    ),
                )?;
            }

            // Synchronize
            self.device.synchronize()?;

            // Copy device → host
            let mut host_parity = vec![0u8; m_usize * shard_size];
            self.device.dtoh_sync_copy_into(&d_parity, &mut host_parity)?;

            // Convert flat to Vec<Bytes> — zero-copy via Bytes::copy_from_slice
            let parity: Vec<Bytes> = (0..m_usize)
                .map(|row| {
                    let start = row * shard_size;
                    Bytes::copy_from_slice(&host_parity[start..start + shard_size])
                })
                .collect();

            Ok(parity)
        })();

        match result {
            Ok(parity) => Ok(parity),
            Err(e) => {
                tracing::error!(error = %e, "GPU encode failed");
                self.mark_unavailable();
                Err(EcError::DecodingFailed(format!("GPU encode error: {e}")))
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Decoder implementation
// ---------------------------------------------------------------------------

impl Decoder for CudaBackend {
    fn decode(
        &self,
        available_shards: &[Option<&[u8]>],
        data_count: u8,
        parity_count: u8,
    ) -> oceanfs_ec::Result<Vec<bytes::Bytes>> {
        let _ = self.is_available();
        let encoder = oceanfs_ec::CauchyEncoder::new(oceanfs_core::CodecConfig {
            data_shards: data_count,
            parity_shards: parity_count,
            ..Default::default()
        });
        encoder.decode(available_shards, data_count, parity_count)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn cuda_backend_probe() {
        let config = GpuConfig::default();
        let backend = CudaBackend::new(config);
        if let Some(ref b) = backend {
            assert!(b.is_available());
        }
    }

    #[test]
    fn gpu_config_stored() {
        let config = GpuConfig { device_id: 0, ..Default::default() };
        if let Some(backend) = CudaBackend::new(config) {
            assert_eq!(backend.config().device_id, 0);
        }
    }

    #[test]
    fn should_use_gpu_respects_threshold() {
        let config = GpuConfig { min_segment_size: 100, ..Default::default() };
        if let Some(backend) = CudaBackend::new(config) {
            assert!(!backend.should_use_gpu(50));
            assert!(backend.should_use_gpu(200));
        }
    }

    #[test]
    fn mark_unavailable() {
        let config = GpuConfig::default();
        if let Some(backend) = CudaBackend::new(config) {
            assert!(backend.is_available());
            backend.mark_unavailable();
            assert!(!backend.is_available());
        }
    }

    #[test]
    fn gf_mul_split_table_correct() {
        for coeff in 1..=255u8 {
            let table = GfMulTable::new(coeff);
            for b in 0..=255u8 {
                let lo_idx = (b & 0x0F) as usize;
                let hi_idx = (b >> 4) as usize;
                let reconstructed = table.lo[lo_idx] ^ table.hi[hi_idx];
                assert_eq!(reconstructed, gf_mul_portable(coeff, b));
            }
        }
    }

    #[test]
    fn gpu_tables_build() {
        let tables = GpuEncodeTables::new(4, 2);
        assert_eq!(tables.k, 4);
        assert_eq!(tables.m, 2);
        assert_eq!(tables.data.len(), 256);
    }

    #[test]
    fn gf_mul_identity() {
        for a in 1..=255u8 {
            assert_eq!(gf_mul_portable(a, 1), a);
        }
    }

    /// Full GPU encode + CPU decode roundtrip test.
    /// Runs only when a CUDA GPU is available.
    #[test]
    fn encode_gpu_decode_cpu_roundtrip() {
        let config = GpuConfig { min_segment_size: 0, ..Default::default() };
        let backend = match CudaBackend::new(config) {
            Some(b) => b,
            None => {
                eprintln!("SKIP: no CUDA device");
                return;
            }
        };

        let data: Vec<Vec<u8>> = (0..4).map(|i| vec![i; 256]).collect();
        let shard_refs: Vec<&[u8]> = data.iter().map(|v| v.as_slice()).collect();

        let parity = backend.encode(&shard_refs, 2).unwrap();
        assert_eq!(parity.len(), 2);
        assert_eq!(parity[0].len(), 256);

        // Cross-backend: decode via CPU
        let available: Vec<Option<&[u8]>> = vec![
            None,
            Some(&data[1]),
            Some(&data[2]),
            Some(&data[3]),
            Some(&parity[0]),
            Some(&parity[1]),
        ];
        let recovered = backend.decode(&available, 4, 2).unwrap();
        assert_eq!(recovered[0], data[0]);
    }
}
