[package]
name = "oceanfs-benches"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "dummy.rs"

[[bench]]
name = "ec_benchmark"
harness = false
path = "ec_benchmark.rs"

[[bench]]
name = "hash_benchmark"
harness = false
path = "hash_benchmark.rs"

[[bench]]
name = "storage_benchmark"
harness = false
path = "storage_benchmark.rs"

[[bench]]
name = "io_benchmark"
harness = false
path = "io_benchmark.rs"

[dependencies]
blake3.workspace = true
bytes.workspace = true
criterion.workspace = true
oceanfs-core.workspace = true
oceanfs-ec.workspace = true
oceanfs-storage.workspace = true
tempfile = "3"
tokio.workspace = true
